python/core-workflow

cherry_picker/readme.rst

Correctly reference the core-workflow repo.

Update cherry_picker readme

---

cherry_picker/readme.rst

This feature is introduced in https://github.com/Mariatta/chic_a_cherry_picker/pull/12 but undocumented.

Document how to execute cherry_picker.py from cpython dir

---

cherry_picker/cherry_picker.py

Closes https://github.com/python/core-workflow/issues/82

Fix #82: allow running directly from CPython dir again

---

cherry_picker/readme.rst

Background: https://mail.python.org/pipermail/core-workflow/2017-May/000991.html

Remove the step about applying cherry-pick label

---

cherry_picker/cherry_picker.py

Print out commit message after continuing

---

cherry_picker/readme.rst

Apply code style to --dry-run option (issue #121)

---

cherry_picker/readme.rst
setup.py

Add version info in setup.py
Cleanup readme
Uploaded to testpypi: https://testpypi.python.org/pypi/cherry_picker/
#114

Updates to cherry_picker readme, for PyPI

---

README.md
cherry_picker/readme.rst

Add Python version badge, PyPI version badge, and travis build badge:

Add Badges to cherry_picker readme

---

cherry_picker/cherry_picker/cherry_picker.py

e.g. happens if the current working branch has uncommitted changes.

Exit if cherry_picker failed to checkout branch

---

README.rst

This PR creates a (preliminary) list of core workflow tools 🔧  as indicated by #164. 
Please, if some other core-workflow tools are missing, indicate it and I will be more than happy to add them. 😃 
The rendering of the `rst` file can be checked [here](https://github.com/pablogsal/core-workflow/blob/issue-164/README.rst).

Create a list of tools we use with the new workflow. Solves #164

---

cherry_picker/cherry_picker/cherry_picker.py

Prefix the Pull Request title if it wasn't in the commit message.
Part two for fixing https://github.com/python/miss-islington/issues/38

cherry_picker: Prefix the pull request title

---

cherry_picker/readme.rst

Remove the license badge.

---

cherry_picker/cherry_picker/__init__.py

Bump cherry_picker's version.

---

cherry_picker/cherry_picker/cherry_picker.py
cherry_picker/cherry_picker/test.py

Move dry_run printout into CherryPicker constructor as well.
Consider it as a preparation for adding config file #225 
Repository SHA used for CPython repo sanity check should be configurable for using the tool for another repo like aiohttp.
Later we'll do reading the value from config file

Move repository sanity check into CherryPicker class.

---

cherry_picker/readme.rst

Update cherry-picker config example.

Fix readme: toml requires lower-cased true/false for bools

---

.gitignore
cherry_picker/cherry_picker/cherry_picker.py
cherry_picker/cherry_picker/test.py
cherry_picker/readme.rst

Support version retrieval from custom branches

---

cherry_picker/readme.rst

Add a changelog for PRs 264, 265, and 266.

---

.travis.yml

Ref travis-ci/travis-conditions#13
Ref https://github.com/python/core-workflow/pull/272#issuecomment-414726306
cc @Mariatta

Hack falsy if-clase in Travis CI config

---

cherry_picker/cherry_picker/__init__.py
cherry_picker/readme.rst

cherry picker post-release updates

---

.travis.yml

Rather than having it under deploy

Put windows job under tests stage

---

.github/ISSUE_TEMPLATE/blurb.md
.github/ISSUE_TEMPLATE/core-workflow.md
.github/ISSUE_TEMPLATE/triage_membership.md

Closes https://github.com/python/core-workflow/issues/349

Create issue templates for blurb, issue triage, or core workflow

---

README.rst

Remove cpython-bpo-linkify link from README

---

.github/ISSUE_TEMPLATE/labels.md

Since there are often proposal about adding/removing/updating labels on `python/cpython`, I created this template in order to formalize the process a bit.  I also added a `labels` label to track this type of issues.

Add an issue template to request label changes.

---

.github/workflows/tests.yml

Same as:
* https://github.com/python/miss-islington/pull/590
* https://github.com/python/bedevere/pull/520
* https://github.com/python/blurb_it/pull/316

Update Python versions in the CI workflow.

---

README.md

Replaces and closes https://github.com/python/core-workflow/pull/483.
See also https://github.com/python/devguide/pull/1538.

Update info about new CLA bot
