python/core-workflow

cherry_picker/readme.rst

Venv as included in the Python 3.6 stdlib works just fine.

Drop the virtualenv dependency

---

cherry_picker/readme.rst

Accidentally introduced `python3` usage over `python` in a previous commit.

Make the use of `python` consistent

---

cherry_picker/cherry_picker.py
cherry_picker/readme.rst

- prints git commands that would be executed if
everything runs without errors
- also prints the PR creation URLs that would be opened
- does NOT do any local checkouts, cherry-picks, branch
creation or branch deletion
- does NOT actually create any PRs
Also includes a few associated changes related to getting
helpful dry-run output with my configuration:
* prevents stderr output when checking for 'upstream' remote
* new '--push' option to specify PR remote (I use
origin/pr rather than upstream/origin for fetch/push)
* adds a 'backport-' prefix to the PR branch names
Closes https://github.com/python/core-workflow/issues/52

Issue #52: Add a --dry-run option

---

cherry_picker/cherry_picker.py
cherry_picker/readme.rst
cherry_picker/requirements.txt
cherry_picker/test.py

Lots of changes here:
- Added` --abort` and `--continue` options
(Described in https://github.com/python/core-workflow/pull/65)
- Added `--status` option, will do git status in the CPython dir
- Automatically prefix the commit title with `[X.Y] `
- Automatically replace `#<PR-ID>` with `GH-<PR-ID>`
- Wrote some more tests
Closes https://github.com/python/core-workflow/issues/44
Closes https://github.com/python/core-workflow/issues/45

Add --abort/--continue, --status, auto prefix commit msg with [X.Y]

---

cherry_picker/__main__.py
cherry_picker/cherry_picker.py

Relate to #64 #69 
*I'm not sure if this change will break other bot or something.*
This commit make cherry-picker more easier to use, you don't need to let `cpython` folder under `cherry_picker` anymore.
Example:
```
$ ls
cpython   # Assume we already clone cpython in our dev dir and upstream setting
$ git clone https://github.com/python/core-workflow.git
$ cd core-workflow
$ python -m venv venv
$ source venv/bin/activate
(venv) $ python -m pip install -r cherry_picker/requirements.txt
(venv) $ cp -r cherry_picker venv/lib/python3.6/site-packages/
(venv) $ cd ..
(venv) $ python -m cherry_picker deadbeaf 3.6
```

Make cherry picker as a script

---

cherry_picker/readme.rst

Closes https://github.com/python/core-workflow/issues/77

Clarify how to find the commit hash for cherry_picker.py

---

cherry_picker/cherry_picker.py
cherry_picker/readme.rst

When supplied, changes won't be pushed to remote.
Use --continue or --abort afterwards.
Document --no-push option
Modify --abort behavior, ensuring that only branch
created by cherry-picker.py gets deleted.
Closes https://github.com/python/core-workflow/issues/78

Add --no-push option

---

cherry_picker/cherry_picker.py

Closes https://github.com/python/core-workflow/issues/88
```
$ python -m cherry_picker -h
Usage: cherry_picker.py [OPTIONS] [COMMIT_SHA1] [BRANCHES]...
Options:
--dry-run           Prints out the commands, but not executed.
--push REMOTE       git remote to use for PR branches
--abort             Abort current cherry-pick and clean up branch
--continue          Continue cherry-pick, push, and clean up branch
--status            Get the status of cherry-pick
--push / --no-push  Changes won't be pushed to remote
-h, --help          Show this message and exit.
```

Support `-h`

---

cherry_picker/cherry_picker.py
cherry_picker/readme.rst
setup.cfg
setup.py

``venv/bin/pip install .`` installs all dependencies and
venv/bin/cherry_picker script.
Signed-off-by: Christian Heimes <christian@python.org>
Closes https://github.com/python/core-workflow/issues/50
Closes https://github.com/python/core-workflow/issues/64
Closes https://github.com/python/core-workflow/issues/89

Add setup.py

---

cherry_picker/readme.rst

By default, my venv did not have wheel installed, so I needed to install it before running the pip install for cherry_picker.
Closes https://github.com/python/core-workflow/issues/103

Add instructions to README for cherry_picker to install wheel

---

cherry_picker/cherry_picker.py
cherry_picker/readme.rst

The new --push/--no-push option conflicts with the old name
of the option for setting the PR remote.
This updates the latter option to the more explicit
`--pr-remote`.

Rename PR remote option to --pr-remote

---

cherry_picker/cherry_picker.py
cherry_picker/readme.rst

- my remotes are over ssh://  which was not handled.
- my remote don't have the .git extension .. for whatever reason.
- --push REMOTE was conflicting with --push/--no-push so I renamed the
former one to --remote and updated the readme accordingly.
I believe @Mariatta wrote most of that, so your review would be welcome.

Fix a couple of issues when using the cherry-picker:

---

.travis.yml

`-v` makes it easier to see that any added tests are indeed running as expected.

Make tests verbose on Travis

---

cherry_picker/cherry_picker.py
cherry_picker/test.py

I've been carrying around a patch that removed the `.git` from the end of `username_end =` line, but it broke with a recent pull, motivating me to fix it properly and submit it.
@Carreau, could you confirm that the `ssh://` URLs I included in the test match what yours look like that you mentioned in #104?

Simplify username parsing

---

cherry_picker/cherry_picker.py

- only allow `cherry_pick --continue` if the current branch is a backport branch
- use `git rev-parse --abbrev-ref HEAD`
instead of `git symbolic-ref HEAD | sed 's!refs\/heads\/!!'` when retrieving branch names

cherry_picker.py bug fixes

---

setup.cfg

cherry_picker.py is not universal

---

cherry_picker/readme.rst

Update readme with pip install instructions

---

blurb/blurb.py

Change adding Python 3.5 support.

Replace f-string with "...".format(...)

---

cherry_picker/cherry_picker/cherry_picker.py
cherry_picker/cherry_picker/test.py

It can now be run from anywhere in CPython repo.
The logic to detect if we are in CPython repo or not, is borrowed from blurb.
This removes the functionality where it tries to `cd` to a cpython directory within cherry_picker.

cherry_picker now can only be run from CPython repo

---

cherry_picker/cherry_picker/__init__.py
cherry_picker/cherry_picker/__main__.py
cherry_picker/cherry_picker/cherry_picker.py
cherry_picker/flit.ini

`click` doesn't recognize the version set in` __init__.py` 😞  so it has to be hardcoded.

Set cherry_picker to v 0.1.0.dev1

---

blurb/blurb.py

If the user aborted the operation by hitting Control+C, abort the
operation without a traceback.
Example run:
$ blurb
(Terminate editor without any change)
Error: Error in /tmp/tmpt0etkaf2.rst:26:
Blurb 'body' text must not be empty!
[Hit return to retry (or Ctrl-C to abort)> ^C
$

Abort "blurb add" cleanly

---

cherry_picker/cherry_picker/cherry_picker.py

This is needed before https://github.com/python/miss-islington/pull/1 can be merged.

raise errors in cherrypicker

---

cherry_picker/cherry_picker/cherry_picker.py

Keep the existing functionality that by default the backport commit
message will be prefixed with [X.Y].
Part one for fixing https://github.com/python/miss-islington/issues/38

cherry_picker: add a flag if backport commit msg should be prefixed

---

blurb/blurb.py

EDITOR might contain spaces.  If it does, is that
just a path with spaces?  Or is it a command-line with
arguments?  blurb now handles all these cases.

Issue #162: make blurb sophisticated about EDITOR.

---

cherry_picker/cherry_picker/cherry_picker.py
cherry_picker/cherry_picker/test.py

Fixes https://github.com/python/core-workflow/issues/219

Add another empty line before the Co-Authored-by line.

---

blurb/blurb.py

These would have made my first experience using blurb just now smoother.
- Make `blurb --help` work in addition to `blurb help`. This is my default command for figuring out how to use a command; for example, `mypy --help`, `pip --help`, and `flit --help` all give me useful info.
- Suggest looking at `blurb help` if the user gave an invalid command.

blurb: small usability improvements

---

blurb/blurb.py

Users might have a .gitignore configuration where they ignore folders like "Lib", "Build" "Misc" or other paths that might lead to blurb not being able to add the files using just "git add". This change makes git to "force" the addition of the files passed in, ensuring that even if present in gitignore they will be added to the commit, rather than blurb just failing in the operation.
Sending the patch as it just happened to me 😄

Add -f to blurb to include files even if ignored

---

cherry_picker/cherry_picker/cherry_picker.py

Users can configure what strategy "git push" uses to determine which
remote branch it should push to.  Cherry-picker doesn't work with all of
the git push strategies but we can make explicit what the remote branch
should be which works around that problem.
In my case, I had this in my .gitconfig (perhaps needed long ago when git used a less intuitive push strategy by default:
```
[push]
default = tracking
```
That caused git to push to the remote that the branch was branched from rather than trying to push to a branch with the same name as the existing, local one.  Being explicit about both the local and remote branchname should just make the behaviour cherry_picker expects work in both default git configurations and customzed configurations.

Explicit push location to ignore user git config

---

cherry_picker/cherry_picker/cherry_picker.py
cherry_picker/cherry_picker/test.py

cherry_picker has recently grown support for prefixed version branches
(like stable-2.6).  The --continue support had a bug with those branches
where it wouldn't account for the fact that those branches could have
extra dashes in them and thus mixing branch name with sha.
This commit should fix those situations.

Fix detection of upstream version branches with continue

---

cherry_picker/cherry_picker/cherry_picker.py
cherry_picker/cherry_picker/test.py

When running cherry_picker --continue we count on being able to get
certain information from the branch's name which cherry_picker
constructed earlier.  Verify as best we can that the branch name is one
which cherry_picker could have constructed.
Relies on the changes here: #265
(which does the work of one of the validations)

Validate a branch that we parse when running cherry_picker --continue 

---

.travis.yml

Resolves #222
@Mariatta you still need to update secret and probably add @brettcannon's account for blurb.
Some hacks present are trying to work around limitations described in travis-ci/dpl#822

👷📦🚀 Enable Travis CI to publish dists to PYPI

---

blurb/blurb.py

In #275, I described an issue where a CalledProcessError occurs but no indication is reported, a condition that likely would have been reported if the output hadn't been suppressed.
Although a simple retry worked around the issue, it may happen again in the future, and it would be nice to know what is the cause. This change enables that.
In the third commit, this change also uses the long-form option to git, making it easier for someone troubleshooting an issue like this one unfamiliar with the meaning of `-f` to understand what's happening.

Better reporting in adverse conditions

---

cherry_picker/cherry_picker/cherry_picker.py
cherry_picker/pyproject.toml

Allow to install cherry_picker with the modern click version

Relax click dependency.

---

cherry_picker/cherry_picker/cherry_picker.py
cherry_picker/cherry_picker/test.py
cherry_picker/readme.rst

Implement storing runtime state in repo level Git config

---

.travis.yml
cherry_picker/cherry_picker/test.py

I've set up a Windows build on Travis before, maybe I can help #296 a bit!
There's no Python pre-installed, but there's a package manager, `choco`, that can install it.
Currently, the tests fail because they seem to require Git's `user.email` and `user.name` to be set globally. They fail on my dev machine as well, since I don't have an e-mail set globally (I use different e-mail addresses on different repos).
Sadly, I can't devote time to fixing that issue, but I can help to reproduce or explain more if needed.
To try out changes privately, here's what I do:
* [Enable Travis on your fork](https://travis-ci.org/account/repositories) of the repo
* Uncheck "Build pused branches" and "Build pushed pull requests" on your fork's Travis settings (you'll want to trigger builds manually)
* Push …

cherry-picker: Run Travis CI test on Windows

---

utils/triage_team.py

This should only be run (manually) one time. It requires a core dev's GitHub personal access token.
Closes #334

Script for creating the Python triage team

---

utils/promote_to_triager.py

Would be nice to have this as a bot.
API documentation: https://developer.github.com/v3/teams/members/#add-or-update-team-membership
Script can be run by an admin/owner of the Python GitHub org.

Script for promoting people to Python triage team.

---

blurb/blurb.py

This speeds up the build of the Python documentation
quite a bit, since the NEWS file is huge and causes
sphinx to rebuild its doctree each time the doc
is built, regardless of the other changes

blurb: don't overwrite output when not necessary

---

blurb/blurb.py
blurb/pyproject.toml

By dropping the `f()` function (and dropping Python 3.5
compatibility), as the real `f-string` do not have the issue with
non-locals.
closes #299, #300, #283

Fix: KeyError 'filename'.

---

.github/ISSUE_TEMPLATE/triage_membership.md

The devguide [suggests](https://github.com/python/devguide/pull/889/files) that owners should be mentioned when adding new members, so it would make sense to add the mention to the template.
@python/organization-owners, is it a good idea, or are you getting notifications some other way?

Mention org owners in the new triager template

---

README.rst

Since this tool is archived and no longer used I don't think it should be in the README anymore.

Change CLA bot link from ``the-knights-who-say-ni`` to ``ambv/cla-bot``

---

blurb/blurb.py

I noticed in python/cpython#92448 that the output shows `gh-issues-NNNN:` instead of `gh-NNNN:`.  I had initially proposed to use `gh-issue` instead of just `issue` in the content of the entry because in that case is ambiguous and people might have added the bpo number.  In the output there is no such problem, and `gh-NNNN` is enough.
AFAIU if this PR is applied, it will update older news entries too, right?

Replace `gh-issue-NNNN:` with `gh-NNNN:` in the output

---

.github/workflows/tests.yml

Allow testing feature branches, so contributors can check CI passes _before_ opening a PR.
Add `workflow_dispatch` to add a button, so builds can be manually triggered via the UI (like we could with Travis).
Test Python `3.11-dev`, the latest alpha/beta/RC.
Bump actions to `v3` and cache pip.

Update GitHub Actions

---

.github/ISSUE_TEMPLATE/triage_membership.md

Remove "bpo username" from the table: even if new triagers have BPO usernames, I don't think we need this information any more.
Add "Request for Python triage membership: name" as a title for the template, so it's prefilled when creating a new request issue.

Update fields for triage membership template

---

blurb/blurb.py

This PR supersedes gh-291. A quote from https://github.com/python/core-workflow/pull/291#issuecomment-423268895 for context:
> If we wanted to accommodate CPython forks, we should not 'bless' Tauthon only. /`Py`/`.`/ would potentially also accommodate things like 'Brython'. But it is not clear to me that we want to do this, as it would subvert part of the apparent purpose of the function that uses the RE.
@terryjreedy I believe that `This is Python version 2.7 as modified and augmented by the xxx fork thereof` wording is long and clumsy, and so perceived as *This is Python something something... Looks like a wrong repo*.

Loosen README check for CPython forks

---

README.rst
blurb/pyproject.toml

To match most of the other https://github.com/python repos, let's use `main` as the default branch.
Please could @python/organization-owners rename it?
Docs here: 
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

Rename default branch from "master" to "main"

---

blurb/blurb.py
blurb/tests/fail/invalid-gh-number.rst
blurb/tests/fail/invalid-section.rst
blurb/tests/fail/no-gh-number.rst
blurb/tests/fail/no-section.rst

We now:
* Check the entries in metadata in order, so we complain about the *first* one that has an error, which is a more familiar user experience.
* Have checks for:
* Invalid issue number
* Invalid section
* Empty section
* Completely missing section
(There is no test for "missing issue number", because it's legal to have a Blurb with no issue number.  "no changes" blurbs don't have an issue number.  But we do now reliably test that, *if* the issue number is specified, it *is* correctly formatted.)

Improved error checking when parsing a Blurb.

---

.github/workflows/tests.yml
blurb/README.rst
blurb/pyproject.toml

Re: https://devguide.python.org/versions/

blurb: Drop support for EOL Python 3.7

---

blurb/blurb.py
blurb/tests/fail/small-gh-number.rst
blurb/tests/pass/basic.rst
blurb/tests/pass/basic.rst.res
blurb/tests/pass/case-insensitive.rst
blurb/tests/pass/case-insensitive.rst.res
blurb/tests/pass/no-break-long-words.rst
blurb/tests/pass/no-break-long-words.rst.res
blurb/tests/pass/no-break-on-hyphens.rst
blurb/tests/pass/no-break-on-hyphens.rst.res

Fixes https://github.com/python/core-workflow/issues/504.
Iterates through the template file to find the gh-issue line and checks number if it's in the accepted issue number range.
This is how an unsuccessful attempt looks like:
```sh
❯ /bin/python3 /path/core-workflow/blurb/blurb.py
Error: The gh-issue number should be 32426 or above.
[Hit return to retry (or Ctrl-C to abort)>
```

Accept GitHub issues numbered only 32426 or above

---

.coveragerc
.github/workflows/tests.yml
blurb/blurb.py
blurb/tests/test_blurb.py

This splits out the testing added in https://github.com/python/core-workflow/pull/499 to its own PR, to make reviewing of both easier.
These tests are useful even if #499 is not merged.

blurb: Add tests and run on CI

---

.github/workflows/lint.yml
.github/workflows/tests.yml
.pre-commit-config.yaml
blurb/pyproject.toml
blurb/tox.ini

The tox tool makes it easy to test by taking care of the virtualenv for you and installing dependencies (defined by a `tests` "extra"). It also makes it easy to test multiple Python versions.
For example:
```sh
tox -e py312
tox -e py312 -- --stepwise
tox
tox -p auto
```
This PR also:
* Adds support for Python 3.13
* Updates `pyproject.toml` to use standard metadata instead of tool-specific (flit), so we can add a `tests` extra to `[project.optional-dependencies]`
* Adds simple pre-commit config for linting, and to the CI

Add tox for easy testing of many Python versions
